language: cpp
clone_depth: 100
notifications:
  email: false
env:
  global:
    - FAV_LANG=LISP
    - secure: "H8T44wYbwrfzAl7gH81KSG0McVD2HlshivKT14G6M453lcfQtYRlvMiqGMNoj0gR0evmhD2u0zvvEOsMjtB/RiqnMGgGNNKiT3rFgcZnKsb+2B0EcV0Hs0tehqD39XRc7eZ98aCggoIN2PGRY9UyAZpUWXlppITmjM9cEjT8ZPh4lAcESElhBRErgK/jsdFmLm0Xqa4OweEB+hiCIq5Cj3KUuJXLoIh6wYGsDa9SP2FYnU9t4GPb0aznpjYXJWzQaZs6bEcqv3US0Ao9ZWG+4wgOp1/pmXzhoNq7gR807MMSzPKJ6PsRd9RUYcZEZoLEZJIMFQb+OmaEoOZ3gtg7v+tiPbJaFtXIaG7VKJJ7608jYgF8h/x3PBlMkXKy6A7HBWPl78ekpKWfg1z++KEOLAcXOmPfXsn3GCz4mxboAjjvnkrcHy3dSHPXCyd94z7IGWCR7/88hxudANpqDFb7yWmxNpLvkKa1inRvamunHRKtsdOwvm74iUrkhauqA3T36qbAwGLVFYbxIEpznHKMQeHQmrL7TYHn2RPMf1YWcPqKTpxJJXKfshQH8moHKCfbZYJXQzrFcyn/PXglJRyyWrIGuxrQsXa7kaHR+JKZsLOpDJ6ZYHitWL1ogmUnMPYsHr3RUNqU+PFWhNCvNyJl6yixPn1bJlLF8KNzDqWm5f4="
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode7
      env: PROCESSOR_ARCHITECTURE=x86_64
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: PROCESSOR_ARCHITECTURE=x86_64
before_install:
  - rvm install 2.0.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install gfortran; fi

script:
  - mkdir build
  - cd build
  - cmake -DPROCESSOR_ARCHITECTURE=$PROCESSOR_ARCHITECTURE ..
  - make -j
  - ctest
  - ruby ../scripts/run_test.rb
