language: cpp
clone_depth: 100
notifications:
  email: false
env:
  global:
    - RT_URL=github.com/big-ladder/kiva-test-results.git
    - TEST_DIR=build/test/results
    - RT_DIR=scripts/regress
    secure: "Iu96o6rugFB7LdIGAY8+Yr2ChIZiLGmyWoX6CtXBfu72ZZZcI4G8QMLyh8ymPMBIoq6e7FQOiHyn0TGuPsutwOasnDIKvasP1Duy4hDmO8394uWnv0P2icWNBny7A+cv8mIby/BJ2hB0SlqkCGPi5+L+66FOTZMSw7KWoOxFIsd8RRha4nBY27flGrbcd+nTjyXXSlY6TLP/cpktucB600JCOwbHhV0RqYqd2IIAYKMJTWRVACu42oQqmxqO+T9HP0n0MlV2bbY7PgGEii79wieeaeaVyWdEWPN8fxEqeu8iXfYI3vijXo7IuDLm5kOpPoMFM+OyOWHzFJ0zsFkbJixE7V3F8qEVCiYFI+myGTrCnRSqD3jD0+GQjklj9P1+vmO0D9TBrH66z7YLL9t5E2lGOLJWnNI1uJoUKPTO+BrBvR4sOWuie3fBXCfMDbUr0N4uBfjnVSSAdHvjLf25pN3gkXEpptjSFjJ74blMVswHw9QlCQ4eXN+FGgoLhY2QpzPLpMFmH5ZX5R7r4jktqqNHy4rziM5R9Jxbdf9Gt4kjm0Uc4tEC4iohbTgGlDKIjZPcA2dP4QMCiuidXD80jl+KDSqaOHONB9urf2U0StFEmuJApbQ96gVo+a7/uEgb0izCnOv2V1BbGcQcgWrx7JkCipbae7Lsz/8Of4hqgXI="
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode7
      env: PROCESSOR_ARCHITECTURE=x86_64 COMPILER=clang BUILD_ARCHITECTURE=macosx-clang-x86_64
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: PROCESSOR_ARCHITECTURE=x86_64 COMPILER=gcc BUILD_ARCHITECTURE=linux-gnu-x86_64
before_install:
  - rvm install 2.0.0
  - gem install bundler
  - cd scripts && bundle install && cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install gfortran; fi

script:
  - ruby -e "puts(RUBY_PLATFORM)"
  - SRC_BRANCH=$TRAVIS_BRANCH
  - mkdir build
  - cd build
  - cmake -DPROCESSOR_ARCHITECTURE=$PROCESSOR_ARCHITECTURE ..
  - make -j
  - cd ../scripts
  - bundle exec ruby run-kiva.rb ../build/kiva ../examples/slab.yaml ../weather/USA_DC_Washington.epw ../build/test/results/${BUILD_ARCHITECTURE}/slab/out.csv
  - bundle exec ruby run-kiva.rb ../build/kiva ../examples/basement.yaml ../weather/USA_IL_Chicago.epw ../build/test/results/${BUILD_ARCHITECTURE}/basement/out.csv
  - bundle exec ruby run-kiva.rb ../build/kiva ../examples/crawlspace.yaml ../weather/USA_FL_Tampa.epw ../build/test/results/${BUILD_ARCHITECTURE}/crawlspace/out.csv
  - bundle exec ruby log-results.rb
