init:
  - cmd: echo %PROCESSOR_ARCHITECTURE%
  - cmd: cmake --version

skip_branch_with_pr: true
clone_depth: 100

cache:
  - i686-5.3.0-release-win32-dwarf-rt_v4-rev0.7z
  - x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z

environment:
  RT_URL: github.com/michael-okeefe/test.git
  RT_DIR: scripts/regress
  TEST_DIR: build/test/results
  PATOKEN:
    secure: 8H6cZZJc7y+QdOniRvwDc+1MmmVBuVe+0BABlCWSZZPbE0emW/hAaobJrZV9XHo2
  matrix:
    - GENERATOR: "MinGW Makefiles"
      MINGW_DIR: mingw32
      CONFIG: Release
      COMPILER: MinGW
      BIT: i686
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.3.0/threads-win32/dwarf/i686-5.3.0-release-win32-dwarf-rt_v4-rev0.7z/download
      MINGW_ARCHIVE: i686-5.3.0-release-win32-dwarf-rt_v4-rev0.7z
    - GENERATOR: "MinGW Makefiles"
      MINGW_DIR: mingw64
      CONFIG: Release
      COMPILER: MinGW
      BIT: x86_64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-win32/seh/x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z/download
      MINGW_ARCHIVE: x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z
    - GENERATOR: "Visual Studio 12"
      CONFIG: Release
      COMPILER: MSVC
      platform: x86
      BIT: i686
    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release
      COMPILER: MSVC
      platform: x64
      BIT: x86_64

install:
  - if "%COMPILER%"=="MinGW" (if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%")
  - if "%COMPILER%"=="MinGW" (7z x -y "%MINGW_ARCHIVE%" > nul)
  - if "%BIT%" == "i686" (set PATH=C:\Ruby200\bin;%PATH%)
  - if "%BIT%" == "x86_64" (set PATH=C:\Ruby200-x64\bin;%PATH%)
  - cd scripts
  - bundle install
  - cd ..

before_build:
  - if "%COMPILER%"=="MinGW" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%;%CD%\%MINGW_DIR%\bin")
  - if "%COMPILER%"=="MinGW" (g++ --version)
  - if "%COMPILER%"=="MinGW" (mingw32-make --version)
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - mkdir build
  - cd build
  - if "%COMPILER%"=="MSVC" (cmake "-G%GENERATOR%" "-DPROCESSOR_ARCHITECTURE=%BIT%" ..)
  - if "%COMPILER%"=="MSVC" (cmake --build . --config "%CONFIG%" -- /m)
  - if "%COMPILER%"=="MSVC" (ctest -C "%CONFIG%")
  - if "%COMPILER%"=="MinGW" (cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE="%CONFIG%" "-DPROCESSOR_ARCHITECTURE=%BIT%" ..)
  - if "%COMPILER%"=="MinGW" (cmake --build . -- -j)
  - if "%COMPILER%"=="MinGW" (ctest)
  - cd ../scripts
  - bundle exec ruby regress-test.rb
