init:
  - cmd: cmake --version

skip_branch_with_pr: true
clone_depth: 50

environment:
  matrix:
    - GENERATOR: "MinGW Makefiles"
      MINGW_DIR: "C:\\MinGW\\bin"
      CONFIG: Release
      COMPILER: MinGW
    - GENERATOR: "MinGW Makefiles"
      MINGW_DIR: "C:\\mingw-w64\\i686-5.3.0-posix-dwarf-rt_v4-rev0\\mingw32\\bin"
      CONFIG: Release
      COMPILER: MinGW
    - GENERATOR: "Visual Studio 12"
      CONFIG: Release
      COMPILER: MSVC
    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release
      COMPILER: MSVC

before_build:
  - echo "%COMPILER% %GENERATOR% %CONFIG%"
  #- if "%COMPILER%"=="MinGW" (del "C:\Program Files (x86)\Git\bin\sh.exe")
  - if "%COMPILER%"=="MinGW" (set PATH="%MINGW_DIR%";"%PATH%")
  - if "%COMPILER%"=="MinGW" (g++ --version)
  - if "%COMPILER%"=="MinGW" (mingw32-make --version)

build_script:
  - if "%COMPILER%"=="MSVC" (cmake "-G%GENERATOR%" -H. -B_builds)
  - if "%COMPILER%"=="MSVC" (cmake --build _builds --config "%CONFIG%")
  - if "%COMPILER%"=="MinGW" (cmake "-G%GENERATOR%" -H. -B_builds -DCMAKE_BUILD_TYPE=%CONFIG%")
  - if "%COMPILER%"=="MinGW" (cmake --build _builds -- -j)
