site_name: Kiva
#site_url: http://bigladdersoftware.com
#site_description: Foundation Heat Transfer Calculation Tool.
#site_author: Neal Kruis

#repo_url: https://github.com/nealkruis/kiva/

pages:
- Home: index.md
- Getting Started: getting-started.md
- Input Description:
	- Simulation Control: simulation-control.md

copyright: Copyright &copy; 2015 <a href="http://bigladdersoftware.com">Big Ladder Software</a>
