site_name: Kiva
site_url: http://bigladdersoftware.com
site_description: Foundation Heat Transfer Calculation Tool.
site_author: Neal Kruis

repo_url: https://github.com/nealkruis/kiva/

pages:
- Home: index.md
- Getting Started: getting-started.md
- Input Description: input-def/input-def.md
	- Simulation Control: input-def/simulation-control.md
- Testing: testing.md
- References: references.md

copyright: Copyright &copy; 2015 <a href="http://bigladdersoftware.com">Big Ladder Software</a>
