site_name: Kiva
#site_url: http://bigladdersoftware.com
#site_description: Foundation Heat Transfer Calculation Tool.
#site_author: Neal Kruis

#repo_url: https://github.com/nealkruis/kiva/

#pages:
#- Home: README.md

copyright: Copyright &copy; 2015 <a href="http://bigladdersoftware.com">Big Ladder Software</a>
